"""rename address

Revision ID: 90d35acb2711
Revises: dc3160ef7707
Create Date: 2024-10-03 19:44:58.138487

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90d35acb2711"
down_revision = "dc3160ef7707"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###