"""rename department

Revision ID: dc3160ef7707
Revises: aaf11a693927
Create Date: 2024-10-03 19:41:54.878926

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc3160ef7707"
down_revision = "aaf11a693927"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")  # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###